version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: eu-north-1
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - aws-s3/sync:
          from: dist
          to: 's3://oliver-pd-test/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
